# Generated by Django 4.0.4 on 2022-05-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='type',
        ),
        migrations.AddField(
            model_name='travel',
            name='cityBeach',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
