# Generated by Django 4.0.4 on 2022-05-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='destinationimage',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
