# Generated by Django 4.0.4 on 2022-05-21 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='name',
        ),
        migrations.AddField(
            model_name='travel',
            name='destination_image',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='VisitedLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.travel')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
