# Generated by Django 4.0.4 on 2022-05-20 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0002_travel_destinationimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedLocations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.travel')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
