# Generated by Django 4.0.4 on 2022-05-20 15:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0003_visitedlocations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitedLocations',
            new_name='VisitedLocation',
        ),
        migrations.RenameField(
            model_name='visitedlocation',
            old_name='user_id',
            new_name='username',
        ),
    ]
