# Generated by Django 4.0.4 on 2022-05-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_rename_visitedlocations_visitedlocation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='destinationimage',
            new_name='destination_image',
        ),
        migrations.RenameField(
            model_name='visitedlocation',
            old_name='location_id',
            new_name='location_name',
        ),
    ]
