# Generated by Django 4.0.4 on 2022-05-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_remove_travel_name_travel_destination_image_and_more'),
        ('travel', '0005_rename_destinationimage_travel_destination_image_and_more'),
    ]

    operations = [
    ]
