# Generated by Django 4.0.4 on 2022-05-25 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('continent', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.continent')),
            ],
        ),
        migrations.CreateModel(
            name='CityorBeach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityorbeach', models.CharField(max_length=100)),
                ('continent', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.continent')),
                ('country', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.country')),
            ],
        ),
    ]
